config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions, :registrations], controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  root 'dashboards#index'

  resources :categories
  resources :movies
  resources :ratings
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'MovieDB', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to root_path, class: 'nav-link' do %>Home <span class="sr-only">(current)</span><% end %>
      </li>
      <% if current_user && current_user.admin? %>
      <li class="nav-item">
        <%= link_to 'movie categories', categories_path, class: 'nav-link' %>
      </li>
      <% end %>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= email_to_name(current_user.email) %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'my movies', movies_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'log out', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'sign in', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'sign up', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>